[feat] adds envio as supported data indexer
sei-protocol/sei-docs-old pull request #109
Opened 2024-08-05 15:06 UTC by SvenMuller95

## What is the purpose of the change?

add new content based on https://github.com/sei-protocol/sei-docs/pull/88

fixes merge conflict https://github.com/sei-protocol/sei-docs/pull/88

2024-08-05 15:06 UTC, SvenMuller95 commented
@cordt-sei created this PR in favour of https://github.com/sei-protocol/sei-docs/pull/88

2024-08-26 03:34 UTC, cordt-sei reviewed
Looks good, please note we will be migrating these to a whole new expanded section for third party/community contributions in the near future.

2024-08-26 03:36 UTC, cordt-sei approved these changes

2024-09-14 00:46 UTC, seiyan-writer requested changes

2024-09-14 00:46 UTC, seiyan-writer commented on pages/dev-ecosystem-providers/indexers/indexers.mdx
> +Envio is a modern, multi-chain EVM blockchain indexing framework speed-optimized for querying real-time and historical data.
```suggestion
Envio is a modern, multi-chain EVM blockchain indexing framework, speed-optimized for querying real-time and historical data. Learn more in the [official Envio Docs](https://docs.envio.dev/docs/contract-import).
```

2024-09-14 00:46 UTC, seiyan-writer commented on pages/dev-ecosystem-providers/indexers/indexers.mdx
> +   - [Envio Docs](https://docs.envio.dev/docs/contract-import)
```suggestion
```

2024-10-23 14:49 UTC, SvenMuller95 commented
Hey @cordt-sei @seiyan-writer , is this PR all good to go ? Please let me know 🙏 

Would it also be possible to change Envio from 'infrastructure' to 'data & analytics" label / category on the ecosystem?
<img width="829" alt="Screenshot 2024-10-23 at 16 48 08" src="https://github.com/user-attachments/assets/0a2376ab-4e18-456e-866f-1787fa1f78be">

2024-10-25 21:18 UTC, cordt-sei commented
It looks like this page is being dynamically generated from somewhere else now.

@partyparrotgreg where can @SvenMuller95 make this PR now?

2024-11-04 10:57 UTC, closed without merging