Allowlist tutorial
sei-protocol/sei-docs-old pull request #135
Opened 2024-09-13 17:12 UTC by dssei

## What is the purpose of the change?

Adds new tutorial

## Describe the changes to the documentation

Tutorial is for the new token factory based tokens feature (add-on) - allow list

2024-09-13 18:28 UTC, seiyan-writer requested changes

2024-09-13 18:28 UTC, ghost commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +First, we need to prepare a list of addresses that are allowed to transfer the token and save it to a JSON file.
```suggestion
1. First, create a JSON file that contains the list of addresses you want to include in your allow list.
```

2024-09-13 18:28 UTC, ghost commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +seid tx tokenfactory create-denom $DENOM --from=$ACCOUNT --allow-list=$ALLOW_LIST_FILE_PATH --chain-id=arctic-1 --node=https://rpc.arctic-1.seinetwork.io/ --broadcast-mode=block --fees=20000usei
```suggestion
seid tx tokenfactory create-denom $SUBDENOM \
  --allow-list=$ALLOW_LIST_FILE_PATH \
  --from=$CREATOR_ACCOUNT \
  --chain-id=$CHAIN_ID \
  --fees=$FEE_AMOUNT \
  --gas=$GAS_LIMIT \
  -y
```

2024-09-13 18:28 UTC, ghost commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +```bash copy
```suggestion
```bash
```

2024-09-13 18:28 UTC, ghost commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +This command creates a new coin with specific allow list.
```suggestion
For example:

```bash
seid tx tokenfactory create-denom mytoken \
  --allow-list=./allow_list.json \
  --from mykey \
  --chain-id sei-chain \
  --fees 10000usei \
  --gas auto \
  -y
```

This creates a new token called 'mytoken' with a designated allow list specified in `allow_list.json`.
```

2024-09-13 18:28 UTC, ghost commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +Where each address is a valid Sei bech32 address or EVM 0x prefixed address. Please note, that 0x addresses will be converted to bech32 addresses when the allow list is persisted.
```suggestion
> Ensure that all addresses are valid SEI (Bech32) or EVM (0x-prefixed) addresses. Note that 0x addresses will be converted to Bech32 addresses when the allow list is persisted.
> The maximum number of addresses allowed in the allow list is 2000 by default. This can be configured by the chain administrator.
```

2024-09-13 18:28 UTC, ghost commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +
```suggestion
2. Create a new denom with the specified allow list.
```

2024-09-13 18:28 UTC, ghost commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +## Updating Token Allow List
```suggestion
## Updating an Existing Denom Allowlist
```

2024-09-13 18:28 UTC, ghost commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +As you have learned form the [Token Factory tutorial](tokenfactory-tutorial.mdx), the `tokenfactory` module enables any account to create new tokens with a unique identifier based on the creator's ad
This is a nice / friendly intro. Since it's a tutorial, we might consider adjusting the writing style to make it more direct, something like:

```
The Sei Token Factory module enables token creators to restrict who can interact with their custom tokens through the use of allowlists.
```

And maybe start with a list of what to expect to replace "In this tutorial, we will learn how to create a token with an allow list.". Something like:

```
This tutorial will walk you through:

1. Creating a new denom with an allowlist.
2. Updating an existing denom to add or modify an allowlist.
3. Querying the allowlist of a denom.
4. Understanding the configuration and limitations of allowlists.
```

Can also link each section with inline references to the respective headers.

2024-09-13 18:28 UTC, ghost commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +
We could consider placing these in dropdown near the command(s), providing additional info for those seeking more details, without cluttering for users who are focused on the commands and find the command flags intuitive.

And add a link reference to the CLI docs reference.

2024-09-13 18:28 UTC, ghost commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +## Querying Token Allow List
```suggestion
## Querying a Denom Allowlist
```

2024-09-13 18:28 UTC, ghost commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +## Requirements
```suggestion
## Prerequisites
```

2024-09-13 18:28 UTC, ghost commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +- The `seid` CLI
```suggestion
- The `seid` CLI installed.
```

2024-09-13 18:28 UTC, ghost commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +- A wallet with SEI tokens on devnet
```suggestion
- A wallet with SEI tokens on devnet.
- Access to a running Sei blockchain node.
```

2024-09-13 18:28 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +seid tx tokenfactory update-denom $DENOM --from=$ACCOUNT --allow-list=$ALLOW_LIST_FILE_PATH --chain-id=arctic-1 --node=https://rpc.arctic-1.seinetwork.io/ --broadcast-mode=block --fees=20000usei
```suggestion
seid tx tokenfactory update-denom $DENOM \
  --allow-list=$ALLOW_LIST_FILE_PATH \
  --from=$ACCOUNT \
  --chain-id=$CHAIN_ID \
  --node=$NODE_RPC_URL \
  --broadcast-mode=block \
  --fees=$FEE_AMOUNT \
  --gas=$GAS_LIMIT \
  -y
```

2024-09-13 18:28 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +```bash copy
```suggestion
```bash
```

2024-09-13 18:28 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +This command updates the allow list of a token.
```suggestion
For example:
```bash
seid tx tokenfactory update-denom mytoken \
  --allow-list=./updated_allow_list.json \
  --from mykey \
  --chain-id arctic-1 \
  --node https://rpc.arctic-1.seinetwork.io/ \
  --broadcast-mode=block \
  --fees 20000usei \
  --gas auto \
  -y
```

This command updates the allowlist of 'mytoken'.
```

2024-09-13 18:28 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +
Can link example of node RPC to use and can also call out running locally.

2024-09-13 18:28 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +This command creates a new coin with specific allow list.
The example commands suggested in the sections may be unnecessary and could clutter the content. We could also rely on the main code block and incorporate the example.

2024-09-13 18:28 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +```bash copy
```suggestion

```bash
```

2024-09-13 18:28 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +You may query the allow list of a token using the node REST endpoint. E.g.:
```suggestion
You may query the allowlist of a token using the node REST endpoint. E.g.:
```

2024-09-13 18:28 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +# Introducing Token Add-ons
```suggestion
# Token Allowlists
```

2024-09-13 18:28 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +# Introducing Token Add-ons
While it's true that this tutorial is technically introducing token add-ons, since the primary focus is on allowlists, it would make sense to reflect that more directly in the title.

2024-09-13 18:28 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +# Introducing Token Add-ons
This could eventually be part of an add-ons section in the docs.

2024-09-13 18:28 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +To allow all addresses agian to transfer the token, you can simply submit an empty allow list.
```suggestion
To re-enable all addresses to transfer the token, you can simply submit an empty allowlist.
```

2024-09-13 18:28 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +
```suggestion
```

2024-09-13 18:28 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +
In addition, this section could be restructured into "Understanding Allowlist Validations & Limitations," 

Summarizing key aspects and providing a reference point for other sections. For example, when creating the JSON file of addresses, [this](https://github.com/sei-protocol/sei-docs/pull/135/files#diff-e71c3e3d8503032b25c3bfb1219b087164713ed2fca9c58089144e6f671f60c3R36) could be replaced with: "See the 'Understanding Allowlist Validations & Limitations' section for details." which captures the associated details.

```
- **Valid Addresses**: All addresses in the allowlist must be valid in their respective formats (SEI Bech32 or EVM 0x prefixed). Invalid addresses will result in a validation error.
- **Address Conversion**: EVM addresses (0x prefixed) are automatically converted to SEI Bech32 addresses when the allow list is processed.
- **No Duplicates**: Duplicate addresses in the allowlist are not allowed and will result in a validation error.
- **Maximum Size**: By default, the maximum number of addresses allowed in the allowlist is 2,000. This limit can be configured by the chain administrator by setting `DenomAllowListMaxSize`.
- **Non-Empty List**: The allow list cannot be empty when provided. If you wish to remove the allow list, you need to pass an empty JSON object {}.
- And so on...

```

2024-09-13 18:30 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +As you have learned form the [Token Factory tutorial](tokenfactory-tutorial.mdx), the `tokenfactory` module enables any account to create new tokens with a unique identifier based on the creator's ad
On nomenclature -

- I believe we can use "allowlist" instead of "allow list", similar to "whitelist" (compound noun).
- I believe denom is more accurate instead of token, but token is probably better for things like SEO.

2024-09-13 18:32 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +# Introducing Token Add-ons
Also see [this](https://github.com/sei-protocol/sei-docs/pull/135/files#r1759307446) for suggesting denom.

2024-09-13 18:36 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +To update the allow list of a token, you can use the following command:
```suggestion
1. To update the allowlist of a token, you can use the following command:
```

2024-09-14 00:52 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +```json
A nit - as we have numbered these sections, the codeblocks should be indented so they are properly formatted underneath the point.

2024-09-14 00:53 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +2. Create a new denom with the specified allow list.
```suggestion

2. Create a new denom with the specified allow list.
```

2024-09-14 00:53 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +```bash
```suggestion

```bash
```

2024-09-14 00:53 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +### Understanding Command Line Arguments
```suggestion

### Understanding Command Line Arguments
```

2024-09-14 00:53 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +```bash
```suggestion
```bash

```

2024-09-14 00:53 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +To re-enable all addresses to transfer the token, you can simply submit an empty allowlist.
```suggestion
To re-enable all addresses to transfer the token, you can simply submit an empty allowlist.

```

2024-09-14 00:53 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +````
```suggestion
```
```

2024-09-16 19:04 UTC, seiyan-writer approved these changes

2024-09-16 19:04 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +	```json
```suggestion
    ```json
```

2024-09-16 19:04 UTC, seiyan-writer commented on pages/dev-tutorials/tokenfactory-allow-list.mdx
> +	```json
I think spacing should be 4 width instead of 8 (as its too indented)
<img width="1035" alt="image" src="https://github.com/user-attachments/assets/3a74b316-9802-48ef-a496-bc769b437659">

2024-10-10 22:50 UTC, besated approved these changes

2024-10-10 22:50 UTC, merged