Modfiy to create v1 docs
sei-protocol/sei-docs-old pull request #29
Opened 2024-03-01 15:47 UTC by mj850

2024-03-01 23:47 UTC, besated requested changes

2024-03-01 23:47 UTC, besated commented on pages/index.mdx
> +Sei is the fastest parallel Layer 1 blockchain, optimized for trading.
think we might need to update the language here - let's consult growth on this

2024-03-01 23:47 UTC, besated commented on pages/getting-tokens/mainnet-tokens.mdx
> +  These tokens addresses are also available in our registry on GitHub.
can you link to the registry here: https://github.com/sei-protocol/chain-registry/blob/main/assetlist.json

2024-03-01 23:47 UTC, besated commented on pages/interacting-with-sei/ecosystem-apps.mdx
> +## Featured Dapps
this page might not be necessary i think we should just link to https://www.sei.io/ecosystem

2024-03-01 23:47 UTC, besated commented on pages/interacting-with-sei/signing-transactions.mdx
> +You can use Compass or Leap wallet to sign trasactions on Sei.
lets do "Compass or Fin"

2024-03-01 23:47 UTC, besated commented on pages/interacting-with-sei/signing-transactions.mdx
> +## Setting Up your Sei wallet.
nit: remove period at the end

2024-03-01 23:47 UTC, besated commented on pages/overview.mdx
> +Find out more on our [website](https://www.sei.io/)
nit: add period at the end

2024-03-01 23:47 UTC, besated commented on pages/overview.mdx
> +If you are an EVM developer, you can find the docs for our EVM compatible public devnet [here](https://v2.docs.sei.io/)
nit: add period at the end

2024-03-01 23:47 UTC, besated commented on pages/overview.mdx
> +Sei is a general purpose, open-source Layer 1 blockchain specialized for the exchange of digital assets. Leveraging a novel consensus and technical breakthroughs, Sei is the fastest blockchain in the
same with language here, we'll likely have to consult with growth

2024-03-01 23:47 UTC, besated commented on theme.config.tsx
> +  primaryHue: 0,
what are the default values of this? is this for the colors i assume

2024-03-02 01:16 UTC, mj850 commented on theme.config.tsx
> +  primaryHue: 0,
![image](https://github.com/sei-protocol/sei-docs/assets/27497046/d7be2d0f-688b-4359-a92a-616e98699bc6)
The default is Blue - this primaryHue setting changes the colors of links and the nav bar on the side

2024-03-02 01:28 UTC, mj850 commented on theme.config.tsx
> +  primaryHue: 0,
Actually blue seems a bit easier on the eyes. lmk what you think

2024-03-07 21:56 UTC, mj850 commented on pages/index.mdx
> +Sei is the fastest parallel Layer 1 blockchain, optimized for trading.
Updated overview page based on feedback

2024-03-11 22:19 UTC, besated approved these changes
left a couple comments, otherwise lgtm!

2024-03-11 22:19 UTC, besated commented on pages/block-explorers.mdx
> +    - [Seiscan (TestNet)](https://www.seiscan.app/atlantic-2)
typo: "Testnet" instead of "TestNet"

2024-03-11 22:19 UTC, besated commented on pages/getting-tokens/mainnet-tokens.mdx
> +
i think we should also add native usdc (noble) and native usdt (kava) here to - https://github.com/sei-protocol/chain-registry/blob/71938fc346e65df7458e3458f16faab3faf198aa/assetlist.json#L478-L522

2024-03-11 22:19 UTC, besated commented on pages/interacting-with-sei/ecosystem-apps.mdx
> +import levanaLogo from "../../public/assets/logos/levana.jpeg";
i think u can remove these images now since we're just linking to ecosystem page

2024-03-12 02:14 UTC, merged