Add open source resources for docs
sei-protocol/sei-docs-old pull request #45
Opened 2024-04-17 05:58 UTC by mj850

Update README and Styleguide to encourage open source contributions

Add Github workflow to gate merging on validation (just simply building)

2024-04-17 17:49 UTC, besated requested changes
looks good! left a couple comments

2024-04-17 17:49 UTC, besated commented on README.md
> +Ensure you have `yarn` installed (macOS users can Run `brew install yarn`)
the docs actually uses `pnpm` instead of `yarn`, can you update this?

also we'll need to update the github workflow above

2024-04-17 17:49 UTC, besated commented on README.md
> +All content submitted will be reviewed by a maintainer
can u make sure that each PR requires at least one maintainer to review

2024-04-17 20:08 UTC, mj850 commented on README.md
> +Ensure you have `yarn` installed (macOS users can Run `brew install yarn`)
Oh! I've been using yarn the whole time

Just updated with instructions for pnpm

2024-04-17 20:11 UTC, mj850 commented on README.md
> +All content submitted will be reviewed by a maintainer
Added a CODEOWNERS file to specify this, but will probably only take effect when it's merged into main

2024-04-18 22:20 UTC, besated approved these changes
per discussion, let's just stick with `yarn` instead otherwise looks good!

2024-04-18 22:35 UTC, merged