Rework eco + card components, sidebar 'For Users', add/mod user guides
sei-protocol/sei-docs-old pull request #52
Opened 2024-05-06 14:53 UTC by Cordtus

## important changes
Added text filter field on ecosystem/apps page. 
This changes how we add app info. This no longer goes in ./components/EcosystemApps.tsx, it will go in ./data/appData.ts

New entries require another property "tags" which are used to search/filter the apps list as well as generate the text indicating what tags are currently possible to filter by.
```
// appData.ts

// .. imports .. 

// types definition
interface App {
    title: string;
    description: string;
    href: string;
    image: StaticImageData;
    tags: string[];
}
// list of apps
export const appData: App[] = [
    {
        title: "Compass",
        description: "The native DEX on SEI",
        href: "https://compasswallet.io/",
        image: compassLogo,
        tags: ["Wallet", "Native"]
    },
// additional entries
```

### general structure changes

Reorganize left sidebar condense "for users" section and add, reorganize+condense other material, collapse all sidebar menus by default.

2024-05-08 18:59 UTC, Cordtus reviewed
fixed any breaking changes regarding https://github.com/sei-protocol/sei-docs/pull/51/files

2024-05-09 06:58 UTC, mj850 requested changes
Left some comments about small changes that might need to be made.

We should also update the title of this PR (Maybe: "Rework ecosystem component and add user guides").

2024-05-09 06:58 UTC, mj850 commented on components/Card/Card.tsx
> +// Card.tsx
Can remove this comment

2024-05-09 06:58 UTC, mj850 commented on data/appData.ts
> +import siloLogo from "../../public/assets/ecosystem/silo.jpeg";
Think these last 3 links are invalid

2024-05-09 06:58 UTC, mj850 commented on data/appData.ts
> +        tags: ["Wallet", "Native"]
Nit: We should make this list of tags a list of reusable enums
```ts
export enum Tag {
    WALLET = 'Wallet',
    NATIVE = 'Native',
    ...
}
```

Then for each app we can do `tags: [Tag.WALLET, Tag.NATIVE]` and not have to worry about ensuring all the apps have the same spelling, case etc when we add more in the future.

2024-05-09 06:58 UTC, mj850 commented on package.json
> +    "auto-pull": "nodemon --exec 'git pull' --interval 60000"
What is the auto-pull command used for?

2024-05-09 06:58 UTC, mj850 commented on pages/user-guides/getting-tokens.mdx
> +Bridging is essential for transferring tokens between different blockchains. This allows you to utilize tokens from various chains on the Sei network in their wrapped forms. It's crucial to verify th
The official sei app bridge is soon just going to be a bunch of links to other bridging sites. (Like a Bridge finder).

Should we rewrite this to say something like "To find the best bridges in and out of Sei, visit the [official Sei Bridge app](https://app.sei.io/bridge)" instead?

2024-05-09 06:58 UTC, mj850 commented on pages/user-guides/getting-tokens.mdx
> +Faucets are available for acquiring small amounts of tokens on the Sei public devnet (arctic-1) for testing and development:
Not in scope for this changes but our native faucet is now available on both arctic-1 and atlantic-2 at 
atlantic-2.app.sei.io/faucet
arctic-1.app.sei.io/faucet

These are both discord gated.

2024-05-09 06:58 UTC, mj850 commented on pages/user-guides/setting-up-a-wallet.mdx
> +- **EVM Address**: This address starts with `0x` and is used for EVM-based activities.
Nit it doesn't mention on this page what "EVM" refers to. Might be helpful to expand the abbreviation somewhere on this page (Ethereum Virtual Machine (EVM))

2024-05-09 06:58 UTC, mj850 commented on pages/user-quickstart.mdx
> +~~~~~~~~ Ignore below here ~~~~~~~
Is this line actually visible on the docs?

2024-05-09 06:58 UTC, mj850 commented on pages/user-guides/block-explorers.mdx
> +> :warning: **Note**: *In rare cases, some information may be misinterpreted. Off-chain data should be used as a guide only*.
This is showing as:

:warning: Note: In rare cases, some information may be misinterpreted. Off-chain data should be used as a guide only.

Maybe use callout?

<Callout emoji="⚠️">
  Note: In rare cases, some information may be misinterpreted. Off-chain data should be used as a guide only.
</Callout>

2024-05-09 06:58 UTC, mj850 commented on pages/user-guides/linking-addresses.mdx
> +You can link your Sei and EVM / 0x addresses using the Sei app: https://app.sei.io/
Address linking at app.sei.io will go live after mainnet launches. Not sure if we want to make this arctic-1.app.sei.io first in the meantime.

I anticipate we'll need to comb through the docs to add mainnet specific information before the launch too?

2024-05-09 06:58 UTC, mj850 commented on pages/user-quickstart.mdx
> +~~~~~~~~ Ignore below here ~~~~~~~
Looks like this is making things show up weirdly in the docs on this page
![image](https://github.com/sei-protocol/sei-docs/assets/27497046/00e8ad17-4aad-4bce-a8d2-039a35c31658)

2024-05-09 06:58 UTC, mj850 commented on pages/user-quickstart.mdx
> +- **Confirm all of the displayed information carefully:** Before approving any request on the wallet app, ensure the receiving address and amounts are correct.
In the new Sei app, we don't provide briding functionality. Instead we'll show the user a list of 3rd bridges they can use to bridge the asset from the source to destination blockchain.

Can try here at atlantic-2.app.sei.io/bridge

2024-05-09 06:58 UTC, mj850 commented on pages/user-quickstart.mdx
> +- **Confirm all of the displayed information carefully:** Before approving any request on the wallet app, ensure the receiving address and amounts are correct.
Oh I see that the next line explains this. Do we need still need this line then though? 
"- **Confirm all of the displayed information carefully:** Before approving any request on the wallet app, ensure the receiving address and amounts are correct."

2024-05-09 14:19 UTC, Cordtus commented on package.json
> +    "auto-pull": "nodemon --exec 'git pull' --interval 60000"
Removing that, it was so it would auto-pull and build my live hosted local version while we were making changes

2024-05-09 17:42 UTC, duncand0nuts commented on pages/user-guides/getting-tokens.mdx
> +Bridging is essential for transferring tokens between different blockchains. This allows you to utilize tokens from various chains on the Sei network in their wrapped forms. It's crucial to verify th
this whole page is going to be rewritten and yes we will change this wording.

2024-05-09 17:43 UTC, duncand0nuts commented on pages/user-guides/getting-tokens.mdx
> +Faucets are available for acquiring small amounts of tokens on the Sei public devnet (arctic-1) for testing and development:
this will be removed from users section - only devs care about testnet tokens really

2024-05-09 17:44 UTC, duncand0nuts commented on pages/user-guides/setting-up-a-wallet.mdx
> +- **EVM Address**: This address starts with `0x` and is used for EVM-based activities.
this page will be rewritten

2024-05-09 17:50 UTC, Cordtus commented on pages/user-guides/getting-tokens.mdx
> +Bridging is essential for transferring tokens between different blockchains. This allows you to utilize tokens from various chains on the Sei network in their wrapped forms. It's crucial to verify th
Copy that, added blue 'info' callout here.

2024-05-09 18:17 UTC, Cordtus commented on pages/user-guides/getting-tokens.mdx
> +Faucets are available for acquiring small amounts of tokens on the Sei public devnet (arctic-1) for testing and development:
cleaned this up anyway, while I'm here

2024-05-09 18:20 UTC, Cordtus commented on pages/user-guides/linking-addresses.mdx
> +You can link your Sei and EVM / 0x addresses using the Sei app: https://app.sei.io/
new branch to be made to address these types of issue as per Bryan in slack channel

2024-05-09 19:36 UTC, Cordtus commented on pages/user-quickstart.mdx
> +~~~~~~~~ Ignore below here ~~~~~~~
Looked like a rough outline, removed it and I've saved it locally incase anyone wants it.

2024-05-09 19:39 UTC, Cordtus commented on pages/user-quickstart.mdx
> +- **Confirm all of the displayed information carefully:** Before approving any request on the wallet app, ensure the receiving address and amounts are correct.
Meant to emphasize that just the ability to move assets over any given bridge platform to Sei, there may not be any reason to do that or any straightforward way to move it back or even to see it in any wallet or other app.

2024-05-09 19:48 UTC, Cordtus commented on theme.config.tsx
collapses all left sidebar menu directories by default

2024-05-09 19:49 UTC, Cordtus reviewed
resolved all previous comments, added comments for any additional changes

2024-05-09 19:49 UTC, Cordtus commented on components/Card/Card.tsx
> +// Card.tsx
removed

2024-05-09 19:57 UTC, Cordtus commented on data/appData.ts
> +import siloLogo from "../../public/assets/ecosystem/silo.jpeg";
added

2024-05-09 19:59 UTC, Cordtus commented on data/appData.ts
> +import siloLogo from "../../public/assets/ecosystem/silo.jpeg";
fixed paths and added images

2024-05-09 20:00 UTC, Cordtus commented on data/appData.ts
> +        tags: ["Wallet", "Native"]
Created issue for this please feel free to assign me 'Cordt@seifdn.org'

2024-05-09 22:20 UTC, mj850 approved these changes
Looks good! Thanks for making these changes

2024-05-10 00:06 UTC, mj850 approved these changes

2024-05-10 00:23 UTC, merged