add API3 under oracles.mdx
sei-protocol/sei-docs-old pull request #99
Opened 2024-07-02 15:06 UTC by vanshwassan

## What is the purpose of the change?

Added [API3](https://api3.org/) under `dev-ecosystem-providers/oracles.mdx` 

## Describe the changes to the documentation

Basic developer docs and references for using API3's price feeds on Sei and accessing the [API3 Market](https://market.api3.org/sei). 

## Notes

N.A.

2024-07-05 17:37 UTC, cordt-sei commented
Please add to the bottom of the list to keep the list in chronological order.

2024-09-14 00:44 UTC, seiyan-writer requested changes

2024-09-14 00:44 UTC, seiyan-writer commented on pages/dev-ecosystem-providers/oracles.mdx
> +The [API3 Market](https://market.api3.org/) provides access to 200+ price feeds on [Sei Mainnet](https://market.api3.org/sei) and [Testnet](https://market.api3.org/sei-testnet). The price feeds opera
```suggestion
The [API3 Market](https://market.api3.org/) offers access to over 200 price feeds on both Sei [Mainnet](https://market.api3.org/sei) and [Testnet](https://market.api3.org/sei-testnet). These price feeds function as a native push oracle and can be activated instantly via the Market UI.
```

2024-09-14 00:44 UTC, seiyan-writer commented on pages/dev-ecosystem-providers/oracles.mdx
> +Unlike traditional data feeds, reading [API3 price feeds](https://docs.api3.org/guides/dapis/) enables dApps to auction off the right to update the price feeds to searcher bots which facilitates more
```suggestion
Unlike traditional data feeds, accessing [API3 price feeds](https://docs.api3.org/guides/dapis/) allows dApps to auction off the right to update the feeds to searcher bots, improving the efficiency of liquidation processes for users and LPs in DeFi money markets. The recaptured OEV is returned to the dApp.
```

2024-09-18 20:55 UTC, cordt-sei commented on pages/dev-ecosystem-providers/oracles.mdx
> +Unlike traditional data feeds, reading [API3 price feeds](https://docs.api3.org/guides/dapis/) enables dApps to auction off the right to update the price feeds to searcher bots which facilitates more
I think `allows dApps to auction` should be `allow dApps to auction`

2024-10-20 14:41 UTC, cordt-sei commented
Hey @vanshwassan can you check the conflicts and requested changes?

2024-10-30 04:58 UTC, seiyan-writer commented
May we also avoid adding the yarn.lock file

2024-11-14 14:15 UTC, cordt-sei commented
Seems abandoned

2024-11-14 14:15 UTC, closed without merging